CREATE TABLE orders(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY(START WITH 1),
  date_created DATE,
  user_id INT,
  goods_id INT,
  amount DOUBLE
  );

ALTER TABLE orders ADD CONSTRAINT fk_goods_id
FOREIGN KEY (goods_id)
REFERENCES PUBLIC.goods(id);

